music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^albums/$',views.index, name='albums'),
    url(r'^album/(?P<album_id>[0-9]+)/$', views.album_detail, name='album_detail'),
    url(r'^album/song/(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^album/(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^album/(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^album/(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^album/(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^playlists/$',views.playlists,name='playlists'),
    url(r'^create_playlist/$', views.create_playlist, name='create_playlist'),
    url(r'^playlist/(?P<playlist_id>[0-9]+)/delete_playlist/$', views.delete_playlist, name='delete_playlist'),
    url(r'^playlist/(?P<playlist_id>[0-9]+)/$', views.playlist_detail, name='playlist_detail'),
    url(r'^album/(?P<album_id>[0-9]+)/add_song_playlist/$',views.add_song_playlist,name='add_song_playlist'),
    url(r'^playlist/(?P<playlist_id>[0-9]+)/(?P<song_id>[0-9]+)/remove_song_playlist/$', views.remove_song_playlist, name='remove_song_playlist'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^lyrics/(?P<song_id>[0-9]+)/$', views.lyrics, name='lyrics'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    lyricist = models.CharField(default='',max_length=250)
    singers = models.CharField(default='',max_length=250)
    lyrics_file = models.FileField(default='')
    #lyric = models.TextField(max_length=1000,default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title



class PlayList(models.Model):
    playlist_title = models.CharField(max_length=100)
    user = models.ForeignKey(User, default=1)

    def __str__(self):
        return self.playlist_title


class PlayListSong(models.Model):
    playlist = models.ForeignKey(PlayList, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.playlist) + ' - ' + str(self.song)


class Language(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Lyrics(models.Model):
    song = models.ForeignKey(Song,on_delete=models.CASCADE)
    language = models.ForeignKey(Language)
    #language = models.CharField(max_length=1000)
    lyric = models.TextField(max_length=1000)

    def __str__(self):
        return str(self.song) + ' - ' + str(self.language)

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song, PlayList, PlayListSong


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class PlayListForm(forms.ModelForm):

    class Meta:
        model = PlayList
        fields = ['playlist_title']


class PlayListSongForm(forms.ModelForm):

    class Meta:
        model = PlayListSong
        fields = ['playlist', 'song']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import AlbumForm, SongForm, UserForm, PlayListForm ,PlayListSongForm
from .models import Album, Song, PlayList, PlayListSong,Lyrics

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_album(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_album.html', context)
            album.save()
            return render(request, 'music/album_detail.html', {'album': album})
        context = {
            "form": form,
        }
        return render(request, 'music/create_album.html', context)


def create_song(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if form.is_valid():
            albums_songs = album.song_set.all()
            for s in albums_songs:
                if s.song_title == form.cleaned_data.get("song_title"):
                    context = {
                        'album': album,
                        'form': form,
                        'error_message': 'You already added that song',
                    }
                    return render(request, 'music/create_song.html', context)
            song = form.save(commit=False)
            song.album = album
            song.audio_file = request.FILES['audio_file']
            file_type = song.audio_file.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Audio file must be WAV, MP3, or OGG',
                }
                return render(request, 'music/create_song.html', context)

            song.save()
            return render(request, 'music/album_detail.html', {'album': album})
        else:
            context = {
                'album': album,
                'form': form,
            }
            return render(request, 'music/create_song.html', context)


def delete_album(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        album = Album.objects.get(pk=album_id)
        album.delete()
        albums = Album.objects.all()
        return render(request, 'music/index.html', {'albums': albums})


def delete_song(request, album_id, song_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        album = get_object_or_404(Album, pk=album_id)
        song = Song.objects.get(pk=song_id)
        song.delete()
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'music/album_detail.html', {'album': album})


def album_detail(request, album_id):
        album = get_object_or_404(Album, pk=album_id)
        return render(request, 'music/album_detail.html', {'album': album})


def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    albums = Album.objects.all()
    song_results = Song.objects.all()
    query = request.GET.get("q")
    if query:
        albums = albums.filter(
            Q(album_title__icontains=query) |
            Q(artist__icontains=query)
        ).distinct()
        song_results = song_results.filter(
            Q(song_title__icontains=query)
        ).distinct()
        return render(request, 'music/index.html', {
            'albums': albums,
            'songs': song_results,
        })

    return render(request, 'music/index.html', {'albums': albums})


def songs(request, filter_by):
        try:
            song_ids = []
            for album in Album.objects.all():
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })


def playlists(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        playlists = PlayList.objects.filter(user=request.user)
        return render(request, 'music/playlists.html', {'playlists': playlists})



def create_playlist(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = PlayListForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            playlists = PlayList.objects.filter(user=request.user)
            return render(request, 'music/playlists.html', {'playlists': playlists})
        else:
            context = {
                "form": form,
            }
            return render(request, 'music/create_playlist.html', context)


def delete_playlist(request, playlist_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        playlist = PlayList.objects.get(pk=playlist_id)
        playlist.delete()
        playlists = PlayList.objects.filter(user=request.user)
        return render(request, 'music/playlists.html', {'playlists': playlists})


def playlist_detail(request,playlist_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        playlist = get_object_or_404(PlayList, pk=playlist_id)
        song_ids = []
        for playlistsong in PlayListSong.objects.filter(playlist=PlayList.objects.filter(id=playlist_id)):
                song_ids.append(playlistsong.song.id)
        songs = Song.objects.filter(pk__in=song_ids)
        return render(request, 'music/playlist_detail.html', {'songs': songs,'playlist':playlist})


def add_song_playlist(request,album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = PlayListSongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if form.is_valid():
            playlistsong = form.save(commit=False)
            playlistsong.save()
            playlists = PlayList.objects.filter(user=request.user)
            return render(request, 'music/album_detail.html', {'album': album})
        else:
            context = {
                "form": form,
            }
            return render(request, 'music/add_song_playlist.html', context)

def remove_song_playlist(request, playlist_id, song_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        playlistsong = PlayListSong.objects.get(song_id=song_id,playlist_id=playlist_id)
        playlistsong.delete()
        playlist = get_object_or_404(PlayList, pk=playlist_id)
        song_ids = []
        for playlistsong in PlayListSong.objects.filter(playlist=PlayList.objects.filter(id=playlist_id)):
            song_ids.append(playlistsong.song.id)
        songs = Song.objects.filter(pk__in=song_ids)
        return render(request, 'music/playlist_detail.html', {'songs': songs,'playlist':playlist})

'''
def add_song_playlist(request,playlist_id,song_id):
    form = PlayListSongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        playlist_songs = PlayListSong.objects.filter(playlist=PlayList.objects.filter(id=playlist_id))
        song = get_object_or_404(Song, pk=song_id)
        playlist = get_object_or_404(PlayList, pk=playlist_id)
        for s in playlist_songs:
            playlist_song = get_object_or_404(Song, pk=s.song.id)
            if song.song_title == playlist_song.song_title:
                context = {
                    'playlist':playlist ,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/album_detail.html', context)
        playlistsong = form.save(commit=False)
        playlistsong.save()

music/templates/music/album_detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style type="text/css">
    .bs-example{
    	margin: 20px;
    }
</style>

{% block body %}

<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:album_detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:album_detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                          <!--  <th>Lyrics File</th> -->
                            <th>lyrics</th>
                            <th>Lyricist</th>
                            <th>Favorite</th>


                        </tr>
                        </thead>


                        <!-- lyric model -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog modal-lg">

                                          <!-- Modal content-->
                                          <div class="modal-content">
                                                <div class="modal-header">
                                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                  <h4 class="modal-title">Lyric</h4>
                                                </div>
                                                <div class="modal-body">
                                                  <p id="lyricBody"></p><p id="demo"></p>
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                </div>
                                          </div>

                            </div>
                        </div>


                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }} </td>


                                <td>

                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                  <!--
                                <td>
                                    <a target="_blank" href="{{ song.lyrics_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-music"></span>&nbsp; Lyrics
                                        </button>
                                    </a>
                                </td>

                               -->
                                <td>
                                     <div class="container col-sm-4 col-md-3">
                                      <!-- Trigger the modal with a button -->


                                      <button type="button" class="btn btn-success btn-xs lyrics" index="{% url 'music:lyrics' song.id %}" musicfile="{{ song.audio_file.url }}">Lyrics</button>



                                    </div>
                                </td>


                                <td>{{ song.lyricist }}</td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>



                            </tr>

                        {% endfor %}
                        {% block javascript %}

                                               <script>
                                                $(".lyrics").click(function(){

                                                   $.get( "http://10.1.1.142:8000"+$(this).attr('index'), function( data ) {

                                                            $("#lyricBody").html(data)

                                                           //document.getElementById("demo").innerHTML = '<html><body><audio controls><source src="http://10.1.1.142:8000'+${{"song.audio_file.url"}}+'/" type="audio/mpeg" /></audio></body></html>';
                                                            document.getElementById("demo").innerHTML = '<html><body><audio controls><source src="http://10.1.1.142:8000'+'/media/01_-_Yaa_Yaa_www.AtoZmp3.in.mp3'+'/" type="audio/mpeg" /></audio></body></html>';

                                                            $("#myModal").modal("show")
                                                   });


                                                 })



                                               </script>
                                          {% endblock %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music Box{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
    {% block javascript %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Box</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
                {% if user.is_authenticated %}
                <li class="{% block playlists_active %}{% endblock %}"><a href="{% url 'music:playlists'  %}"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp; PlayLists</a></li>
                {% endif %}
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block addplaylist_active %}{% endblock %}"><a href="{% url 'music:create_playlist' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add PlayList</a></li>
                <li class="{% block addalbum_active %}{% endblock %}"><a href="{% url 'music:create_album' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album</a></li>
                <li class="{% block username %}{% endblock %}"><a href="{% url 'music:logout_user' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; {{ user.username }}</a></li>
            </ul>
            {% endif %}
            {% if not user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
            {% endif %}
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:album_detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive" width="200" height="200">
                        </a>
                        <div class="caption">
                            <h4>{{ album.album_title }}</h4>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:album_detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:delete_album' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'music:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_album' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:album_detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:album_detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}